// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("0.0.0")]
[assembly: AssemblyFileVersionAttribute("0.0.0")]
[assembly: AssemblyMetadataAttribute("githash","3fc7b26fe203308cf7c1d3c5a84f88c508700279")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.0";
    }
}
