// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("0.0.0.0")]
[assembly: AssemblyFileVersionAttribute("0.0.0.0")]
[assembly: AssemblyMetadataAttribute("githash","e40b7a4045f3594605273a8404b606bfa781b8e5")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.0.0";
    }
}
